# Generated by Django 4.0.3 on 2022-04-17 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_expense_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date_created']},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='payment_date',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.expense')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
