# Generated by Django 4.0.3 on 2022-04-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_expense_options_remove_expense_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='number_of_recurrences',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
